pipeline {
    agent any

    tools {
        nodejs 'node25' 
    }

    stages {
        stage('Install Dependencies') {
            steps {
                dir('frontend') {
                    sh 'npm install'
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('frontend') {
                    sh '''

                    CURRENT_DIR=$(pwd)
                    echo $pwd
                    
                    sudo chmod -R 755 .

                    sudo -u ubuntu pm2 delete express-frontend || true

                    sudo -u ubuntu pm2 start index.js --name "express-frontend"

                    sudo -u ubuntu pm2 list
                    '''
                }
            }
        }
    }
}