pipeline {
    agent any

    stages {
        stage('Setup Environment') {
            steps {
                dir('backend') {
                    sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r requirements.txt
                    '''
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('backend') {
                    sh '''
                    sudo -u ubuntu pm2 delete flask-backend || true
                    sudo -u ubuntu pm2 start app.py --name "flask-backend" --interpreter ./venv/bin/python3
                    sudo -u ubuntu pm2 save
                    '''
                }
            }
        }
    }
}