pipeline {
    agent any

    stages {
        stage('Setup Environment') {
            steps {
                dir('backend') {
                    sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r requirements.txt
                    '''
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('backend') {
                    sh '''
                    CURRENT_DIR=$(pwd)
                    echo $pwd
                    
                    sudo chmod -R 755 .

                    sudo -u ubuntu pm2 delete flask-backend || true

                    sudo -u ubuntu pm2 start ${CURRENT_DIR}/app.py \
                        --name "flask-backend" \
                        --interpreter ${CURRENT_DIR}/venv/bin/python3

                    sudo -u ubuntu pm2 list
                    '''
                }
            }
        }
    }
}